// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: compact_formats.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright (c) 2019-2021 The Zcash developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://www.opensource.org/licenses/mit-license.php .

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Information about the state of the chain as of a given block.
struct ChainMetadata: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// the size of the Sapling note commitment tree as of the end of this block
  var saplingCommitmentTreeSize: UInt32 = 0

  /// the size of the Orchard note commitment tree as of the end of this block
  var orchardCommitmentTreeSize: UInt32 = 0

  /// the size of the Ironwood note commitment tree as of the end of this block
  var ironwoodCommitmentTreeSize: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// A compact representation of a Zcash block.
///
/// CompactBlock is a packaging of ONLY the data from a block that's needed to:
///   1. Detect a payment to your Shielded address
///   2. Detect a spend of your Shielded notes
///   3. Update your witnesses to generate new spend proofs.
///   4. Spend UTXOs associated to t-addresses of your wallet.
///
/// Currently, the `header` field should always be unset (empty). In the future, 
/// the presence or absence of header data may be made dependent on request 
/// parameters, although it is likely that such flexibility will only be provided via 
/// newly-added service methods, not via existing APIs.
struct CompactBlock: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// the height of this block
  var height: UInt64 = 0

  /// if present, the ID (hash) of this block
  var hash: Data = Data()

  /// if present, the ID (hash) of this block's predecessor
  var prevHash: Data = Data()

  /// if non-zero, Unix epoch time when the block was mined
  var time: UInt32 = 0

  /// if present, full header (as returned by the getblock RPC)
  var header: Data = Data()

  /// zero or more compact transactions from this block
  var vtx: [CompactTx] = []

  /// information about the state of the chain as of this block
  var chainMetadata: ChainMetadata {
    get {_chainMetadata ?? ChainMetadata()}
    set {_chainMetadata = newValue}
  }
  /// Returns true if `chainMetadata` has been explicitly set.
  var hasChainMetadata: Bool {self._chainMetadata != nil}
  /// Clears the value of `chainMetadata`. Subsequent reads from it will return its default value.
  mutating func clearChainMetadata() {self._chainMetadata = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _chainMetadata: ChainMetadata? = nil
}

/// A compact representation of a Zcash transaction.
///
/// CompactTx contains the minimum information for a wallet to know if this transaction
/// is relevant to it (either pays to it or spends from it) via shielded elements. Additionally,
/// it can optionally include the minimum necessary data to detect payments to transparent addresses
/// related to your wallet.
struct CompactTx: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The index of the transaction within the block.
  var index: UInt64 = 0

  /// The id of the transaction as defined in
  /// [§ 7.1.1 ‘Transaction Identifiers’](https://zips.z.cash/protocol/protocol.pdf#txnidentifiers)
  /// This byte array MUST be in protocol order and MUST NOT be reversed
  /// or hex-encoded; the byte-reversed and hex-encoded representation is
  /// exclusively a textual representation of a txid.
  var txid: Data = Data()

  /// The transaction fee: present if server can provide. In the case of a
  /// stateless server and a transaction with transparent inputs, this will be
  /// unset because the calculation requires reference to prior transactions.
  /// If there are no transparent inputs, the fee will be calculable as:
  ///    valueBalanceSapling + valueBalanceOrchard + valueBalanceIronwood
  ///    + sum(vPubNew) - sum(vPubOld) - sum(tOut)
  var fee: UInt32 = 0

  var spends: [CompactSaplingSpend] = []

  var outputs: [CompactSaplingOutput] = []

  var actions: [CompactOrchardAction] = []

  var ironwoodActions: [CompactOrchardAction] = []

  /// `CompactTxIn` values corresponding to the `vin` entries of the full transaction.
  ///
  /// Note: the single null-outpoint input for coinbase transactions is omitted. Light
  /// clients can test `CompactTx.index == 0` to determine whether a `CompactTx`
  /// represents a coinbase transaction, as the coinbase transaction is always the
  /// first transaction in any block.
  var vin: [CompactTxIn] = []

  /// A sequence of transparent outputs being created by the transaction.
  var vout: [TxOut] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// A compact representation of a transparent transaction input.
struct CompactTxIn: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The id of the transaction that generated the output being spent. This
  /// byte array must be in protocol order and MUST NOT be reversed or
  /// hex-encoded.
  var prevoutTxid: Data = Data()

  /// The index of the output being spent in the `vout` array of the
  /// transaction referred to by `prevoutTxid`.
  var prevoutIndex: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// A transparent output being created by the transaction.
///
/// This contains identical data to the `TxOut` type in the transaction itself, and
/// thus it is not "compact".
struct TxOut: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The value of the output, in Zatoshis.
  var value: UInt64 = 0

  /// The script pubkey that must be satisfied in order to spend this output.
  var scriptPubKey: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// A compact representation of a [Sapling Spend](https://zips.z.cash/protocol/protocol.pdf#spendencodingandconsensus).
///
/// CompactSaplingSpend is a Sapling Spend Description as described in 7.3 of the Zcash
/// protocol specification.
struct CompactSaplingSpend: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Nullifier (see the Zcash protocol specification)
  var nf: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// A compact representation of a [Sapling Output](https://zips.z.cash/protocol/protocol.pdf#outputencodingandconsensus).
///
/// It encodes the `cmu` field, `ephemeralKey` field, and a 52-byte prefix of the
/// `encCiphertext` field of a Sapling Output Description. Total size is 116 bytes.
struct CompactSaplingOutput: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Note commitment u-coordinate.
  var cmu: Data = Data()

  /// Ephemeral public key.
  var ephemeralKey: Data = Data()

  /// First 52 bytes of ciphertext.
  var ciphertext: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// A compact representation of an [Orchard Action](https://zips.z.cash/protocol/protocol.pdf#actionencodingandconsensus).
struct CompactOrchardAction: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// [32] The nullifier of the input note
  var nullifier: Data = Data()

  /// [32] The x-coordinate of the note commitment for the output note
  var cmx: Data = Data()

  /// [32] An encoding of an ephemeral Pallas public key
  var ephemeralKey: Data = Data()

  /// [52] The first 52 bytes of the encCiphertext field
  var ciphertext: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "cash.z.wallet.sdk.rpc"

extension ChainMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ChainMetadata"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}saplingCommitmentTreeSize\0\u{1}orchardCommitmentTreeSize\0\u{1}ironwoodCommitmentTreeSize\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.saplingCommitmentTreeSize) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.orchardCommitmentTreeSize) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.ironwoodCommitmentTreeSize) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.saplingCommitmentTreeSize != 0 {
      try visitor.visitSingularUInt32Field(value: self.saplingCommitmentTreeSize, fieldNumber: 1)
    }
    if self.orchardCommitmentTreeSize != 0 {
      try visitor.visitSingularUInt32Field(value: self.orchardCommitmentTreeSize, fieldNumber: 2)
    }
    if self.ironwoodCommitmentTreeSize != 0 {
      try visitor.visitSingularUInt32Field(value: self.ironwoodCommitmentTreeSize, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: ChainMetadata, rhs: ChainMetadata) -> Bool {
    if lhs.saplingCommitmentTreeSize != rhs.saplingCommitmentTreeSize {return false}
    if lhs.orchardCommitmentTreeSize != rhs.orchardCommitmentTreeSize {return false}
    if lhs.ironwoodCommitmentTreeSize != rhs.ironwoodCommitmentTreeSize {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CompactBlock: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CompactBlock"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}height\0\u{1}hash\0\u{1}prevHash\0\u{1}time\0\u{1}header\0\u{1}vtx\0\u{1}chainMetadata\0\u{b}protoVersion\0\u{c}\u{1}\u{1}")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.height) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.hash) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.prevHash) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.time) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self.header) }()
      case 7: try { try decoder.decodeRepeatedMessageField(value: &self.vtx) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._chainMetadata) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.height != 0 {
      try visitor.visitSingularUInt64Field(value: self.height, fieldNumber: 2)
    }
    if !self.hash.isEmpty {
      try visitor.visitSingularBytesField(value: self.hash, fieldNumber: 3)
    }
    if !self.prevHash.isEmpty {
      try visitor.visitSingularBytesField(value: self.prevHash, fieldNumber: 4)
    }
    if self.time != 0 {
      try visitor.visitSingularUInt32Field(value: self.time, fieldNumber: 5)
    }
    if !self.header.isEmpty {
      try visitor.visitSingularBytesField(value: self.header, fieldNumber: 6)
    }
    if !self.vtx.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.vtx, fieldNumber: 7)
    }
    try { if let v = self._chainMetadata {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: CompactBlock, rhs: CompactBlock) -> Bool {
    if lhs.height != rhs.height {return false}
    if lhs.hash != rhs.hash {return false}
    if lhs.prevHash != rhs.prevHash {return false}
    if lhs.time != rhs.time {return false}
    if lhs.header != rhs.header {return false}
    if lhs.vtx != rhs.vtx {return false}
    if lhs._chainMetadata != rhs._chainMetadata {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CompactTx: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CompactTx"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}index\0\u{1}txid\0\u{1}fee\0\u{1}spends\0\u{1}outputs\0\u{1}actions\0\u{1}vin\0\u{1}vout\0\u{1}ironwoodActions\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.index) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.txid) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.fee) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.spends) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.outputs) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.actions) }()
      case 7: try { try decoder.decodeRepeatedMessageField(value: &self.vin) }()
      case 8: try { try decoder.decodeRepeatedMessageField(value: &self.vout) }()
      case 9: try { try decoder.decodeRepeatedMessageField(value: &self.ironwoodActions) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.index != 0 {
      try visitor.visitSingularUInt64Field(value: self.index, fieldNumber: 1)
    }
    if !self.txid.isEmpty {
      try visitor.visitSingularBytesField(value: self.txid, fieldNumber: 2)
    }
    if self.fee != 0 {
      try visitor.visitSingularUInt32Field(value: self.fee, fieldNumber: 3)
    }
    if !self.spends.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.spends, fieldNumber: 4)
    }
    if !self.outputs.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.outputs, fieldNumber: 5)
    }
    if !self.actions.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.actions, fieldNumber: 6)
    }
    if !self.vin.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.vin, fieldNumber: 7)
    }
    if !self.vout.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.vout, fieldNumber: 8)
    }
    if !self.ironwoodActions.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.ironwoodActions, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: CompactTx, rhs: CompactTx) -> Bool {
    if lhs.index != rhs.index {return false}
    if lhs.txid != rhs.txid {return false}
    if lhs.fee != rhs.fee {return false}
    if lhs.spends != rhs.spends {return false}
    if lhs.outputs != rhs.outputs {return false}
    if lhs.actions != rhs.actions {return false}
    if lhs.ironwoodActions != rhs.ironwoodActions {return false}
    if lhs.vin != rhs.vin {return false}
    if lhs.vout != rhs.vout {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CompactTxIn: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CompactTxIn"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}prevoutTxid\0\u{1}prevoutIndex\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.prevoutTxid) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.prevoutIndex) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.prevoutTxid.isEmpty {
      try visitor.visitSingularBytesField(value: self.prevoutTxid, fieldNumber: 1)
    }
    if self.prevoutIndex != 0 {
      try visitor.visitSingularUInt32Field(value: self.prevoutIndex, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: CompactTxIn, rhs: CompactTxIn) -> Bool {
    if lhs.prevoutTxid != rhs.prevoutTxid {return false}
    if lhs.prevoutIndex != rhs.prevoutIndex {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension TxOut: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TxOut"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0\u{1}scriptPubKey\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.value) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.scriptPubKey) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.value != 0 {
      try visitor.visitSingularUInt64Field(value: self.value, fieldNumber: 1)
    }
    if !self.scriptPubKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.scriptPubKey, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: TxOut, rhs: TxOut) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.scriptPubKey != rhs.scriptPubKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CompactSaplingSpend: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CompactSaplingSpend"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}nf\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.nf) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.nf.isEmpty {
      try visitor.visitSingularBytesField(value: self.nf, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: CompactSaplingSpend, rhs: CompactSaplingSpend) -> Bool {
    if lhs.nf != rhs.nf {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CompactSaplingOutput: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CompactSaplingOutput"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}cmu\0\u{1}ephemeralKey\0\u{1}ciphertext\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.cmu) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.ephemeralKey) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.ciphertext) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.cmu.isEmpty {
      try visitor.visitSingularBytesField(value: self.cmu, fieldNumber: 1)
    }
    if !self.ephemeralKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.ephemeralKey, fieldNumber: 2)
    }
    if !self.ciphertext.isEmpty {
      try visitor.visitSingularBytesField(value: self.ciphertext, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: CompactSaplingOutput, rhs: CompactSaplingOutput) -> Bool {
    if lhs.cmu != rhs.cmu {return false}
    if lhs.ephemeralKey != rhs.ephemeralKey {return false}
    if lhs.ciphertext != rhs.ciphertext {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension CompactOrchardAction: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CompactOrchardAction"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}nullifier\0\u{1}cmx\0\u{1}ephemeralKey\0\u{1}ciphertext\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.nullifier) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.cmx) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.ephemeralKey) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.ciphertext) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.nullifier.isEmpty {
      try visitor.visitSingularBytesField(value: self.nullifier, fieldNumber: 1)
    }
    if !self.cmx.isEmpty {
      try visitor.visitSingularBytesField(value: self.cmx, fieldNumber: 2)
    }
    if !self.ephemeralKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.ephemeralKey, fieldNumber: 3)
    }
    if !self.ciphertext.isEmpty {
      try visitor.visitSingularBytesField(value: self.ciphertext, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: CompactOrchardAction, rhs: CompactOrchardAction) -> Bool {
    if lhs.nullifier != rhs.nullifier {return false}
    if lhs.cmx != rhs.cmx {return false}
    if lhs.ephemeralKey != rhs.ephemeralKey {return false}
    if lhs.ciphertext != rhs.ciphertext {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
