// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proposal.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// DERIVED FILE -- DO NOT EDIT.
//
// Generated by Scripts/update-proposal-proto.sh from
// zcash/librustzcash/zcash_client_backend/proto/proposal.proto
// at the zcash_client_backend version pinned in Cargo.lock.
//
// The only change from upstream is the added `option swift_prefix` below.
// Bump the dependency and re-run the script rather than editing this file,
// then regenerate proposal.pb.swift.

// Copyright (c) 2023 The Zcash developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://www.opensource.org/licenses/mit-license.php .

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum FfiValuePool: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int

  /// Protobuf requires that enums have a zero discriminant as the default
  /// value. However, we need to require that a known value pool is selected,
  /// and we do not want to fall back to any default, so sending the
  /// PoolNotSpecified value will be treated as an error.
  case poolNotSpecified // = 0

  /// The transparent value pool (P2SH is not distinguished from P2PKH)
  case transparent // = 1

  /// The Sapling value pool
  case sapling // = 2

  /// The Orchard value pool
  case orchard // = 3

  /// The Ironwood value pool (ZIP 2005). Ironwood notes are Orchard-shaped but
  /// belong to a distinct pool; older decoders that do not recognize this value
  /// will reject the proposal rather than misattribute it to Orchard.
  case ironwood // = 4
  case UNRECOGNIZED(Int)

  init() {
    self = .poolNotSpecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .poolNotSpecified
    case 1: self = .transparent
    case 2: self = .sapling
    case 3: self = .orchard
    case 4: self = .ironwood
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .poolNotSpecified: return 0
    case .transparent: return 1
    case .sapling: return 2
    case .orchard: return 3
    case .ironwood: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [FfiValuePool] = [
    .poolNotSpecified,
    .transparent,
    .sapling,
    .orchard,
    .ironwood,
  ]

}

/// The fee rule used in constructing a Proposal
enum FfiFeeRule: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int

  /// Protobuf requires that enums have a zero discriminant as the default
  /// value. However, we need to require that a known fee rule is selected,
  /// and we do not want to fall back to any default, so sending the
  /// FeeRuleNotSpecified value will be treated as an error.
  case notSpecified // = 0

  /// 10000 ZAT
  case preZip313 // = 1

  /// 1000 ZAT
  case zip313 // = 2

  /// MAX(10000, 5000 * logical_actions) ZAT
  case zip317 // = 3
  case UNRECOGNIZED(Int)

  init() {
    self = .notSpecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .notSpecified
    case 1: self = .preZip313
    case 2: self = .zip313
    case 3: self = .zip317
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .notSpecified: return 0
    case .preZip313: return 1
    case .zip313: return 2
    case .zip317: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [FfiFeeRule] = [
    .notSpecified,
    .preZip313,
    .zip313,
    .zip317,
  ]

}

/// A data structure that describes a series of transactions to be created.
struct FfiProposal: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The version of this serialization format.
  var protoVersion: UInt32 = 0

  /// The fee rule used in constructing this proposal
  var feeRule: FfiFeeRule = .notSpecified

  /// The target height for which the proposal was constructed
  ///
  /// The chain must contain at least this many blocks in order for the proposal to
  /// be executed.
  var minTargetHeight: UInt32 = 0

  /// The series of transactions to be created.
  var steps: [FfiProposalStep] = []

  /// The confirmations policy under which the proposal was constructed. It is used to resolve the
  /// anchor for any step that spends no shielded notes (such a step defers the choice of anchor).
  /// Proposals serialized by older versions omit this field; they are interpreted using the
  /// default confirmations policy.
  var confirmationsPolicy: FfiConfirmationsPolicy {
    get {_confirmationsPolicy ?? FfiConfirmationsPolicy()}
    set {_confirmationsPolicy = newValue}
  }
  /// Returns true if `confirmationsPolicy` has been explicitly set.
  var hasConfirmationsPolicy: Bool {self._confirmationsPolicy != nil}
  /// Clears the value of `confirmationsPolicy`. Subsequent reads from it will return its default value.
  mutating func clearConfirmationsPolicy() {self._confirmationsPolicy = nil}

  /// The transaction version header explicitly requested when the proposal was constructed.
  /// Proposals serialized by older versions, or constructed without an explicit version request,
  /// omit this field; they are built at the version implied by the target height.
  var proposedVersion: UInt32 {
    get {_proposedVersion ?? 0}
    set {_proposedVersion = newValue}
  }
  /// Returns true if `proposedVersion` has been explicitly set.
  var hasProposedVersion: Bool {self._proposedVersion != nil}
  /// Clears the value of `proposedVersion`. Subsequent reads from it will return its default value.
  mutating func clearProposedVersion() {self._proposedVersion = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _confirmationsPolicy: FfiConfirmationsPolicy? = nil
  fileprivate var _proposedVersion: UInt32? = nil
}

/// The number of confirmations required before notes may be spent, per ZIP 315.
struct FfiConfirmationsPolicy: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The number of confirmations required before trusted notes may be spent.
  var trusted: UInt32 = 0

  /// The number of confirmations required before untrusted notes may be spent.
  var untrusted: UInt32 = 0

  /// Whether transparent inputs may be spent with zero confirmations in shielding transactions.
  var allowZeroConfShielding: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// A data structure that describes the inputs to be consumed and outputs to
/// be produced in a proposed transaction.
struct FfiProposalStep: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// ZIP 321 serialized transaction request
  var transactionRequest: String = String()

  /// The vector of selected payment index / output pool mappings. Payment index
  /// 0 corresponds to the payment with no explicit index.
  var paymentOutputPools: [FfiPaymentOutputPool] = []

  /// The anchor height to be used in creating the transaction, if any.
  /// Setting the anchor height to zero will disallow the use of any shielded
  /// inputs.
  var anchorHeight: UInt32 = 0

  /// The inputs to be used in creating the transaction.
  var inputs: [FfiProposedInput] = []

  /// The total value, fee value, and change outputs of the proposed
  /// transaction
  var balance: FfiTransactionBalance {
    get {_balance ?? FfiTransactionBalance()}
    set {_balance = newValue}
  }
  /// Returns true if `balance` has been explicitly set.
  var hasBalance: Bool {self._balance != nil}
  /// Clears the value of `balance`. Subsequent reads from it will return its default value.
  mutating func clearBalance() {self._balance = nil}

  /// A flag indicating whether the step is for a shielding transaction,
  /// used for determining which OVK to select for wallet-internal outputs.
  var isShielding: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _balance: FfiTransactionBalance? = nil
}

/// A mapping from ZIP 321 payment index to the output pool that has been chosen
/// for that payment, based upon the payment address and the selected inputs to
/// the transaction.
struct FfiPaymentOutputPool: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var paymentIndex: UInt32 = 0

  var valuePool: FfiValuePool = .poolNotSpecified

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// The unique identifier and value for each proposed input that does not
/// require a back-reference to a prior step of the proposal.
struct FfiReceivedOutput: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var txid: Data = Data()

  var valuePool: FfiValuePool = .poolNotSpecified

  var index: UInt32 = 0

  var value: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// A reference to a payment in a prior step of the proposal. This payment must
/// belong to the wallet.
struct FfiPriorStepOutput: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var stepIndex: UInt32 = 0

  var paymentIndex: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// A reference to a change or ephemeral output from a prior step of the proposal.
struct FfiPriorStepChange: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var stepIndex: UInt32 = 0

  var changeIndex: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// The unique identifier and value for an input to be used in the transaction.
struct FfiProposedInput: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var value: FfiProposedInput.OneOf_Value? = nil

  var receivedOutput: FfiReceivedOutput {
    get {
      if case .receivedOutput(let v)? = value {return v}
      return FfiReceivedOutput()
    }
    set {value = .receivedOutput(newValue)}
  }

  var priorStepOutput: FfiPriorStepOutput {
    get {
      if case .priorStepOutput(let v)? = value {return v}
      return FfiPriorStepOutput()
    }
    set {value = .priorStepOutput(newValue)}
  }

  var priorStepChange: FfiPriorStepChange {
    get {
      if case .priorStepChange(let v)? = value {return v}
      return FfiPriorStepChange()
    }
    set {value = .priorStepChange(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Value: Equatable, Sendable {
    case receivedOutput(FfiReceivedOutput)
    case priorStepOutput(FfiPriorStepOutput)
    case priorStepChange(FfiPriorStepChange)

  }

  init() {}
}

/// The proposed change outputs and fee value.
struct FfiTransactionBalance: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// A list of change or ephemeral output values.
  var proposedChange: [FfiChangeValue] = []

  /// The fee to be paid by the proposed transaction, in zatoshis.
  var feeRequired: UInt64 = 0

  /// The exact number of dummy outputs in each shielded bundle. Omitted by
  /// proposals created before transaction shape was modelled explicitly.
  var dummyOutputs: FfiDummyOutputs {
    get {_dummyOutputs ?? FfiDummyOutputs()}
    set {_dummyOutputs = newValue}
  }
  /// Returns true if `dummyOutputs` has been explicitly set.
  var hasDummyOutputs: Bool {self._dummyOutputs != nil}
  /// Clears the value of `dummyOutputs`. Subsequent reads from it will return its default value.
  mutating func clearDummyOutputs() {self._dummyOutputs = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _dummyOutputs: FfiDummyOutputs? = nil
}

/// Exact per-pool dummy-output counts for the proposed transaction.
struct FfiDummyOutputs: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var sapling: UInt32 = 0

  var orchard: UInt32 = 0

  var ironwood: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// A proposed change or ephemeral output. If the transparent value pool is
/// selected, the `memo` field must be null.
///
/// When the `isEphemeral` field of a `ChangeValue` is set, it represents
/// an ephemeral output, which must be spent by a subsequent step. This is
/// only supported for transparent outputs. Each ephemeral output will be
/// given a unique t-address.
///
/// When the transparent value pool is selected and the `isEphemeral` field
/// is not set, the value represents transparent change, which will be sent
/// to an internal-scope (change) transparent address of the wallet.
struct FfiChangeValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The value of a change or ephemeral output to be created, in zatoshis.
  var value: UInt64 = 0

  /// The value pool in which the change or ephemeral output should be created.
  var valuePool: FfiValuePool = .poolNotSpecified

  /// The optional memo that should be associated with the newly created output.
  /// Memos must not be present for transparent outputs.
  var memo: FfiMemoBytes {
    get {_memo ?? FfiMemoBytes()}
    set {_memo = newValue}
  }
  /// Returns true if `memo` has been explicitly set.
  var hasMemo: Bool {self._memo != nil}
  /// Clears the value of `memo`. Subsequent reads from it will return its default value.
  mutating func clearMemo() {self._memo = nil}

  /// Whether this is to be an ephemeral output.
  var isEphemeral: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _memo: FfiMemoBytes? = nil
}

/// An object wrapper for memo bytes, to facilitate representing the
/// `change_memo == None` case.
struct FfiMemoBytes: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var value: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "cash.z.wallet.sdk.ffi"

extension FfiValuePool: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0PoolNotSpecified\0\u{1}Transparent\0\u{1}Sapling\0\u{1}Orchard\0\u{1}Ironwood\0")
}

extension FfiFeeRule: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0FeeRuleNotSpecified\0\u{1}PreZip313\0\u{1}Zip313\0\u{1}Zip317\0")
}

extension FfiProposal: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Proposal"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}protoVersion\0\u{1}feeRule\0\u{1}minTargetHeight\0\u{1}steps\0\u{1}confirmationsPolicy\0\u{1}proposedVersion\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.protoVersion) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.feeRule) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.minTargetHeight) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.steps) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._confirmationsPolicy) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self._proposedVersion) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.protoVersion != 0 {
      try visitor.visitSingularUInt32Field(value: self.protoVersion, fieldNumber: 1)
    }
    if self.feeRule != .notSpecified {
      try visitor.visitSingularEnumField(value: self.feeRule, fieldNumber: 2)
    }
    if self.minTargetHeight != 0 {
      try visitor.visitSingularUInt32Field(value: self.minTargetHeight, fieldNumber: 3)
    }
    if !self.steps.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.steps, fieldNumber: 4)
    }
    try { if let v = self._confirmationsPolicy {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._proposedVersion {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FfiProposal, rhs: FfiProposal) -> Bool {
    if lhs.protoVersion != rhs.protoVersion {return false}
    if lhs.feeRule != rhs.feeRule {return false}
    if lhs.minTargetHeight != rhs.minTargetHeight {return false}
    if lhs.steps != rhs.steps {return false}
    if lhs._confirmationsPolicy != rhs._confirmationsPolicy {return false}
    if lhs._proposedVersion != rhs._proposedVersion {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FfiConfirmationsPolicy: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ConfirmationsPolicy"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}trusted\0\u{1}untrusted\0\u{1}allowZeroConfShielding\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.trusted) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.untrusted) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.allowZeroConfShielding) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.trusted != 0 {
      try visitor.visitSingularUInt32Field(value: self.trusted, fieldNumber: 1)
    }
    if self.untrusted != 0 {
      try visitor.visitSingularUInt32Field(value: self.untrusted, fieldNumber: 2)
    }
    if self.allowZeroConfShielding != false {
      try visitor.visitSingularBoolField(value: self.allowZeroConfShielding, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FfiConfirmationsPolicy, rhs: FfiConfirmationsPolicy) -> Bool {
    if lhs.trusted != rhs.trusted {return false}
    if lhs.untrusted != rhs.untrusted {return false}
    if lhs.allowZeroConfShielding != rhs.allowZeroConfShielding {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FfiProposalStep: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ProposalStep"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}transactionRequest\0\u{1}paymentOutputPools\0\u{1}anchorHeight\0\u{1}inputs\0\u{1}balance\0\u{1}isShielding\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.transactionRequest) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.paymentOutputPools) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.anchorHeight) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.inputs) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._balance) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.isShielding) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.transactionRequest.isEmpty {
      try visitor.visitSingularStringField(value: self.transactionRequest, fieldNumber: 1)
    }
    if !self.paymentOutputPools.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.paymentOutputPools, fieldNumber: 2)
    }
    if self.anchorHeight != 0 {
      try visitor.visitSingularUInt32Field(value: self.anchorHeight, fieldNumber: 3)
    }
    if !self.inputs.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.inputs, fieldNumber: 4)
    }
    try { if let v = self._balance {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if self.isShielding != false {
      try visitor.visitSingularBoolField(value: self.isShielding, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FfiProposalStep, rhs: FfiProposalStep) -> Bool {
    if lhs.transactionRequest != rhs.transactionRequest {return false}
    if lhs.paymentOutputPools != rhs.paymentOutputPools {return false}
    if lhs.anchorHeight != rhs.anchorHeight {return false}
    if lhs.inputs != rhs.inputs {return false}
    if lhs._balance != rhs._balance {return false}
    if lhs.isShielding != rhs.isShielding {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FfiPaymentOutputPool: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PaymentOutputPool"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}paymentIndex\0\u{1}valuePool\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.paymentIndex) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.valuePool) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.paymentIndex != 0 {
      try visitor.visitSingularUInt32Field(value: self.paymentIndex, fieldNumber: 1)
    }
    if self.valuePool != .poolNotSpecified {
      try visitor.visitSingularEnumField(value: self.valuePool, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FfiPaymentOutputPool, rhs: FfiPaymentOutputPool) -> Bool {
    if lhs.paymentIndex != rhs.paymentIndex {return false}
    if lhs.valuePool != rhs.valuePool {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FfiReceivedOutput: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ReceivedOutput"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}txid\0\u{1}valuePool\0\u{1}index\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.txid) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.valuePool) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.index) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.value) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.txid.isEmpty {
      try visitor.visitSingularBytesField(value: self.txid, fieldNumber: 1)
    }
    if self.valuePool != .poolNotSpecified {
      try visitor.visitSingularEnumField(value: self.valuePool, fieldNumber: 2)
    }
    if self.index != 0 {
      try visitor.visitSingularUInt32Field(value: self.index, fieldNumber: 3)
    }
    if self.value != 0 {
      try visitor.visitSingularUInt64Field(value: self.value, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FfiReceivedOutput, rhs: FfiReceivedOutput) -> Bool {
    if lhs.txid != rhs.txid {return false}
    if lhs.valuePool != rhs.valuePool {return false}
    if lhs.index != rhs.index {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FfiPriorStepOutput: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PriorStepOutput"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}stepIndex\0\u{1}paymentIndex\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.stepIndex) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.paymentIndex) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.stepIndex != 0 {
      try visitor.visitSingularUInt32Field(value: self.stepIndex, fieldNumber: 1)
    }
    if self.paymentIndex != 0 {
      try visitor.visitSingularUInt32Field(value: self.paymentIndex, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FfiPriorStepOutput, rhs: FfiPriorStepOutput) -> Bool {
    if lhs.stepIndex != rhs.stepIndex {return false}
    if lhs.paymentIndex != rhs.paymentIndex {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FfiPriorStepChange: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PriorStepChange"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}stepIndex\0\u{1}changeIndex\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.stepIndex) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.changeIndex) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.stepIndex != 0 {
      try visitor.visitSingularUInt32Field(value: self.stepIndex, fieldNumber: 1)
    }
    if self.changeIndex != 0 {
      try visitor.visitSingularUInt32Field(value: self.changeIndex, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FfiPriorStepChange, rhs: FfiPriorStepChange) -> Bool {
    if lhs.stepIndex != rhs.stepIndex {return false}
    if lhs.changeIndex != rhs.changeIndex {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FfiProposedInput: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ProposedInput"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}receivedOutput\0\u{1}priorStepOutput\0\u{1}priorStepChange\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: FfiReceivedOutput?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .receivedOutput(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .receivedOutput(v)
        }
      }()
      case 2: try {
        var v: FfiPriorStepOutput?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .priorStepOutput(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .priorStepOutput(v)
        }
      }()
      case 3: try {
        var v: FfiPriorStepChange?
        var hadOneofValue = false
        if let current = self.value {
          hadOneofValue = true
          if case .priorStepChange(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.value = .priorStepChange(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.value {
    case .receivedOutput?: try {
      guard case .receivedOutput(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .priorStepOutput?: try {
      guard case .priorStepOutput(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .priorStepChange?: try {
      guard case .priorStepChange(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FfiProposedInput, rhs: FfiProposedInput) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FfiTransactionBalance: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TransactionBalance"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}proposedChange\0\u{1}feeRequired\0\u{1}dummyOutputs\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.proposedChange) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.feeRequired) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._dummyOutputs) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.proposedChange.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.proposedChange, fieldNumber: 1)
    }
    if self.feeRequired != 0 {
      try visitor.visitSingularUInt64Field(value: self.feeRequired, fieldNumber: 2)
    }
    try { if let v = self._dummyOutputs {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FfiTransactionBalance, rhs: FfiTransactionBalance) -> Bool {
    if lhs.proposedChange != rhs.proposedChange {return false}
    if lhs.feeRequired != rhs.feeRequired {return false}
    if lhs._dummyOutputs != rhs._dummyOutputs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FfiDummyOutputs: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DummyOutputs"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}sapling\0\u{1}orchard\0\u{1}ironwood\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.sapling) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.orchard) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.ironwood) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.sapling != 0 {
      try visitor.visitSingularUInt32Field(value: self.sapling, fieldNumber: 1)
    }
    if self.orchard != 0 {
      try visitor.visitSingularUInt32Field(value: self.orchard, fieldNumber: 2)
    }
    if self.ironwood != 0 {
      try visitor.visitSingularUInt32Field(value: self.ironwood, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FfiDummyOutputs, rhs: FfiDummyOutputs) -> Bool {
    if lhs.sapling != rhs.sapling {return false}
    if lhs.orchard != rhs.orchard {return false}
    if lhs.ironwood != rhs.ironwood {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FfiChangeValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ChangeValue"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0\u{1}valuePool\0\u{1}memo\0\u{1}isEphemeral\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.value) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.valuePool) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._memo) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.isEphemeral) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.value != 0 {
      try visitor.visitSingularUInt64Field(value: self.value, fieldNumber: 1)
    }
    if self.valuePool != .poolNotSpecified {
      try visitor.visitSingularEnumField(value: self.valuePool, fieldNumber: 2)
    }
    try { if let v = self._memo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.isEphemeral != false {
      try visitor.visitSingularBoolField(value: self.isEphemeral, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FfiChangeValue, rhs: FfiChangeValue) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.valuePool != rhs.valuePool {return false}
    if lhs._memo != rhs._memo {return false}
    if lhs.isEphemeral != rhs.isEphemeral {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FfiMemoBytes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MemoBytes"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.value) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.value.isEmpty {
      try visitor.visitSingularBytesField(value: self.value, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: FfiMemoBytes, rhs: FfiMemoBytes) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
