// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright (c) 2019-2020 The Zcash developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://www.opensource.org/licenses/mit-license.php .

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// An identifier for a Zcash value pool.
enum PoolType: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case invalid // = 0
  case transparent // = 1
  case sapling // = 2
  case orchard // = 3
  case ironwood // = 4
  case UNRECOGNIZED(Int)

  init() {
    self = .invalid
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .invalid
    case 1: self = .transparent
    case 2: self = .sapling
    case 3: self = .orchard
    case 4: self = .ironwood
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .invalid: return 0
    case .transparent: return 1
    case .sapling: return 2
    case .orchard: return 3
    case .ironwood: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [PoolType] = [
    .invalid,
    .transparent,
    .sapling,
    .orchard,
    .ironwood,
  ]

}

enum ShieldedProtocol: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case sapling // = 0
  case orchard // = 1
  case ironwood // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .sapling
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .sapling
    case 1: self = .orchard
    case 2: self = .ironwood
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .sapling: return 0
    case .orchard: return 1
    case .ironwood: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [ShieldedProtocol] = [
    .sapling,
    .orchard,
    .ironwood,
  ]

}

/// A BlockID message contains identifiers to select a block: a height or a
/// hash. Support for specification by hash is not mandatory. (If `hash` is
/// non-empty, the rpc may return an error.) This field is present to support
/// a possible future upgrade.
struct BlockID: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var height: UInt64 = 0

  var hash: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// BlockRange specifies a series of blocks from start to end inclusive.
/// Both BlockIDs must be heights; specification by hash is not yet supported.
///
/// If no pool types are specified, the server should default to the legacy
/// behavior of returning only data relevant to the shielded (Sapling, Orchard,
/// and Ironwood) pools; otherwise, the server should prune `CompactBlock`s
/// returned to include only data relevant to the requested pool types. Clients MUST
/// verify that the version of the server they are connected to are capable
/// of returning pruned and/or transparent data before setting `poolTypes`
/// to a non-empty value.
struct BlockRange: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var start: BlockID {
    get {_start ?? BlockID()}
    set {_start = newValue}
  }
  /// Returns true if `start` has been explicitly set.
  var hasStart: Bool {self._start != nil}
  /// Clears the value of `start`. Subsequent reads from it will return its default value.
  mutating func clearStart() {self._start = nil}

  var end: BlockID {
    get {_end ?? BlockID()}
    set {_end = newValue}
  }
  /// Returns true if `end` has been explicitly set.
  var hasEnd: Bool {self._end != nil}
  /// Clears the value of `end`. Subsequent reads from it will return its default value.
  mutating func clearEnd() {self._end = nil}

  var poolTypes: [PoolType] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _start: BlockID? = nil
  fileprivate var _end: BlockID? = nil
}

/// A TxFilter contains the information needed to identify a particular
/// transaction: either a block and an index, or a direct transaction hash.
/// Currently, only specification by hash is supported.
struct TxFilter: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// block identifier, height or hash
  var block: BlockID {
    get {_block ?? BlockID()}
    set {_block = newValue}
  }
  /// Returns true if `block` has been explicitly set.
  var hasBlock: Bool {self._block != nil}
  /// Clears the value of `block`. Subsequent reads from it will return its default value.
  mutating func clearBlock() {self._block = nil}

  /// index within the block
  var index: UInt64 = 0

  /// transaction ID (hash, txid)
  var hash: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _block: BlockID? = nil
}

/// RawTransaction contains the complete transaction data. It also optionally includes
/// the block height in which the transaction was included, or, when returned
/// by GetMempoolStream(), the latest block height.
///
/// FIXME: the documentation here about mempool status contradicts the documentation
/// for the `height` field. See https://github.com/zcash/librustzcash/issues/1484
struct RawTransaction: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The serialized representation of the Zcash transaction.
  var data: Data = Data()

  /// The height at which the transaction is mined, or a sentinel value.
  ///
  /// Due to an error in the original protobuf definition, it is necessary to
  /// reinterpret the result of the `getrawtransaction` RPC call. Zcashd will
  /// return the int64 value `-1` for the height of transactions that appear
  /// in the block index, but which are not mined in the main chain. Here, the
  /// height field of `RawTransaction` was erroneously created as a `uint64`,
  /// and as such we must map the response from the zcashd RPC API to be
  /// representable within this space. Additionally, the `height` field will
  /// be absent for transactions in the mempool, resulting in the default
  /// value of `0` being set. Therefore, the meanings of the `height` field of
  /// the `RawTransaction` type are as follows:
  ///
  /// * height 0: the transaction is in the mempool
  /// * height 0xffffffffffffffff: the transaction has been mined on a fork that
  ///   is not currently the main chain
  /// * any other height: the transaction has been mined in the main chain at the
  ///   given height
  var height: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// A SendResponse encodes an error code and a string. It is currently used
/// only by SendTransaction(). If error code is zero, the operation was
/// successful; if non-zero, it and the message specify the failure.
struct SendResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var errorCode: Int32 = 0

  var errorMessage: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Chainspec is a placeholder to allow specification of a particular chain fork.
struct ChainSpec: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Empty is for gRPCs that take no arguments, currently only GetLightdInfo.
struct Empty: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// LightdInfo returns various information about this lightwalletd instance
/// and the state of the blockchain.
struct LightdInfo: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var version: String {
    get {_storage._version}
    set {_uniqueStorage()._version = newValue}
  }

  var vendor: String {
    get {_storage._vendor}
    set {_uniqueStorage()._vendor = newValue}
  }

  /// true
  var taddrSupport: Bool {
    get {_storage._taddrSupport}
    set {_uniqueStorage()._taddrSupport = newValue}
  }

  /// either "main" or "test"
  var chainName: String {
    get {_storage._chainName}
    set {_uniqueStorage()._chainName = newValue}
  }

  /// depends on mainnet or testnet
  var saplingActivationHeight: UInt64 {
    get {_storage._saplingActivationHeight}
    set {_uniqueStorage()._saplingActivationHeight = newValue}
  }

  /// protocol identifier, see consensus/upgrades.cpp
  var consensusBranchID: String {
    get {_storage._consensusBranchID}
    set {_uniqueStorage()._consensusBranchID = newValue}
  }

  /// latest block on the best chain
  var blockHeight: UInt64 {
    get {_storage._blockHeight}
    set {_uniqueStorage()._blockHeight = newValue}
  }

  var gitCommit: String {
    get {_storage._gitCommit}
    set {_uniqueStorage()._gitCommit = newValue}
  }

  var branch: String {
    get {_storage._branch}
    set {_uniqueStorage()._branch = newValue}
  }

  var buildDate: String {
    get {_storage._buildDate}
    set {_uniqueStorage()._buildDate = newValue}
  }

  var buildUser: String {
    get {_storage._buildUser}
    set {_uniqueStorage()._buildUser = newValue}
  }

  /// less than tip height if zcashd is syncing
  var estimatedHeight: UInt64 {
    get {_storage._estimatedHeight}
    set {_uniqueStorage()._estimatedHeight = newValue}
  }

  /// example: "v4.1.1-877212414"
  var zcashdBuild: String {
    get {_storage._zcashdBuild}
    set {_uniqueStorage()._zcashdBuild = newValue}
  }

  /// example: "/MagicBean:4.1.1/"
  var zcashdSubversion: String {
    get {_storage._zcashdSubversion}
    set {_uniqueStorage()._zcashdSubversion = newValue}
  }

  /// Zcash donation UA address
  var donationAddress: String {
    get {_storage._donationAddress}
    set {_uniqueStorage()._donationAddress = newValue}
  }

  /// name of next pending network upgrade, empty if none scheduled
  var upgradeName: String {
    get {_storage._upgradeName}
    set {_uniqueStorage()._upgradeName = newValue}
  }

  /// height of next pending upgrade, zero if none is scheduled
  var upgradeHeight: UInt64 {
    get {_storage._upgradeHeight}
    set {_uniqueStorage()._upgradeHeight = newValue}
  }

  /// version of https://github.com/zcash/lightwallet-protocol served by this server
  var lightwalletProtocolVersion: String {
    get {_storage._lightwalletProtocolVersion}
    set {_uniqueStorage()._lightwalletProtocolVersion = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// TransparentAddressBlockFilter restricts the results of the GRPC methods that
/// use it to the transactions that involve the given address and were mined in
/// the specified block range. Non-default values for both the address and the
/// block range must be specified. Mempool transactions are not included.
///
/// The `poolTypes` field of the `range` argument should be ignored.
/// Implementations MAY consider it an error if any pool types are specified.
struct TransparentAddressBlockFilter: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// t-address
  var address: String = String()

  /// start, end heights only
  var range: BlockRange {
    get {_range ?? BlockRange()}
    set {_range = newValue}
  }
  /// Returns true if `range` has been explicitly set.
  var hasRange: Bool {self._range != nil}
  /// Clears the value of `range`. Subsequent reads from it will return its default value.
  mutating func clearRange() {self._range = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _range: BlockRange? = nil
}

/// Duration is currently used only for testing, so that the Ping rpc
/// can simulate a delay, to create many simultaneous connections. Units
/// are microseconds.
struct Duration: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var intervalUs: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// PingResponse is used to indicate concurrency, how many Ping rpcs
/// are executing upon entry and upon exit (after the delay).
/// This rpc is used for testing only.
struct PingResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var entry: Int64 = 0

  var exit: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Address: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var address: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct AddressList: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var addresses: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Balance: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var valueZat: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Request parameters for the `GetMempoolTx` RPC.
struct GetMempoolTxRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// A list of transaction ID byte string suffixes that should be excluded
  /// from the response. These suffixes may be produced either directly from
  /// the underlying txid bytes, or, if the source values are encoded txid
  /// strings, by truncating the hexadecimal representation of each
  /// transaction ID to an even number of characters, and then hex-decoding
  /// and then byte-reversing this value to obtain the byte representation.
  var excludeTxidSuffixes: [Data] = []

  /// The server must prune `CompactTx`s returned to include only data
  /// relevant to the requested pool types. If no pool types are specified,
  /// the server should default to the legacy behavior of returning only data
  /// relevant to the shielded (Sapling, Orchard, and Ironwood) pools.
  var poolTypes: [PoolType] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// The TreeState is derived from the Zcash z_gettreestate rpc.
struct TreeState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// "main" or "test"
  var network: String = String()

  /// block height
  var height: UInt64 = 0

  /// block id
  var hash: String = String()

  /// Unix epoch time when the block was mined
  var time: UInt32 = 0

  /// sapling commitment tree state
  var saplingTree: String = String()

  /// orchard commitment tree state
  var orchardTree: String = String()

  /// ironwood commitment tree state
  var ironwoodTree: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct GetSubtreeRootsArg: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Index identifying where to start returning subtree roots
  var startIndex: UInt32 = 0

  /// Shielded protocol to return subtree roots for
  var shieldedProtocol: ShieldedProtocol = .sapling

  /// Maximum number of entries to return, or 0 for all entries.
  var maxEntries: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct SubtreeRoot: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The 32-byte Merkle root of the subtree.
  var rootHash: Data = Data()

  /// The hash of the block that completed this subtree.
  var completingBlockHash: Data = Data()

  /// The height of the block that completed this subtree in the main chain.
  var completingBlockHeight: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Results are sorted by height, which makes it easy to issue another
/// request that picks up from where the previous left off.
struct GetAddressUtxosArg: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var addresses: [String] = []

  var startHeight: UInt64 = 0

  /// zero means unlimited
  var maxEntries: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct GetAddressUtxosReply: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var address: String = String()

  var txid: Data = Data()

  var index: Int32 = 0

  var script: Data = Data()

  var valueZat: Int64 = 0

  var height: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct GetAddressUtxosReplyList: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var addressUtxos: [GetAddressUtxosReply] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "cash.z.wallet.sdk.rpc"

extension PoolType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0POOL_TYPE_INVALID\0\u{1}TRANSPARENT\0\u{1}SAPLING\0\u{1}ORCHARD\0\u{1}IRONWOOD\0")
}

extension ShieldedProtocol: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0sapling\0\u{1}orchard\0\u{1}ironwood\0")
}

extension BlockID: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BlockID"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}height\0\u{1}hash\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.height) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.hash) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.height != 0 {
      try visitor.visitSingularUInt64Field(value: self.height, fieldNumber: 1)
    }
    if !self.hash.isEmpty {
      try visitor.visitSingularBytesField(value: self.hash, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BlockID, rhs: BlockID) -> Bool {
    if lhs.height != rhs.height {return false}
    if lhs.hash != rhs.hash {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BlockRange: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BlockRange"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}start\0\u{1}end\0\u{1}poolTypes\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._start) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._end) }()
      case 3: try { try decoder.decodeRepeatedEnumField(value: &self.poolTypes) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._start {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._end {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.poolTypes.isEmpty {
      try visitor.visitPackedEnumField(value: self.poolTypes, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: BlockRange, rhs: BlockRange) -> Bool {
    if lhs._start != rhs._start {return false}
    if lhs._end != rhs._end {return false}
    if lhs.poolTypes != rhs.poolTypes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension TxFilter: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TxFilter"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}block\0\u{1}index\0\u{1}hash\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._block) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.index) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.hash) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._block {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.index != 0 {
      try visitor.visitSingularUInt64Field(value: self.index, fieldNumber: 2)
    }
    if !self.hash.isEmpty {
      try visitor.visitSingularBytesField(value: self.hash, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: TxFilter, rhs: TxFilter) -> Bool {
    if lhs._block != rhs._block {return false}
    if lhs.index != rhs.index {return false}
    if lhs.hash != rhs.hash {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RawTransaction: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RawTransaction"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}data\0\u{1}height\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.data) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.height) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.data.isEmpty {
      try visitor.visitSingularBytesField(value: self.data, fieldNumber: 1)
    }
    if self.height != 0 {
      try visitor.visitSingularUInt64Field(value: self.height, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RawTransaction, rhs: RawTransaction) -> Bool {
    if lhs.data != rhs.data {return false}
    if lhs.height != rhs.height {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SendResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SendResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}errorCode\0\u{1}errorMessage\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.errorCode) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.errorMessage) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.errorCode != 0 {
      try visitor.visitSingularInt32Field(value: self.errorCode, fieldNumber: 1)
    }
    if !self.errorMessage.isEmpty {
      try visitor.visitSingularStringField(value: self.errorMessage, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SendResponse, rhs: SendResponse) -> Bool {
    if lhs.errorCode != rhs.errorCode {return false}
    if lhs.errorMessage != rhs.errorMessage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ChainSpec: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ChainSpec"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: ChainSpec, rhs: ChainSpec) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Empty: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Empty"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Empty, rhs: Empty) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension LightdInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".LightdInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}version\0\u{1}vendor\0\u{1}taddrSupport\0\u{1}chainName\0\u{1}saplingActivationHeight\0\u{1}consensusBranchId\0\u{1}blockHeight\0\u{1}gitCommit\0\u{1}branch\0\u{1}buildDate\0\u{1}buildUser\0\u{1}estimatedHeight\0\u{1}zcashdBuild\0\u{1}zcashdSubversion\0\u{1}donationAddress\0\u{1}upgradeName\0\u{1}upgradeHeight\0\u{1}lightwalletProtocolVersion\0")

  fileprivate class _StorageClass {
    var _version: String = String()
    var _vendor: String = String()
    var _taddrSupport: Bool = false
    var _chainName: String = String()
    var _saplingActivationHeight: UInt64 = 0
    var _consensusBranchID: String = String()
    var _blockHeight: UInt64 = 0
    var _gitCommit: String = String()
    var _branch: String = String()
    var _buildDate: String = String()
    var _buildUser: String = String()
    var _estimatedHeight: UInt64 = 0
    var _zcashdBuild: String = String()
    var _zcashdSubversion: String = String()
    var _donationAddress: String = String()
    var _upgradeName: String = String()
    var _upgradeHeight: UInt64 = 0
    var _lightwalletProtocolVersion: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _version = source._version
      _vendor = source._vendor
      _taddrSupport = source._taddrSupport
      _chainName = source._chainName
      _saplingActivationHeight = source._saplingActivationHeight
      _consensusBranchID = source._consensusBranchID
      _blockHeight = source._blockHeight
      _gitCommit = source._gitCommit
      _branch = source._branch
      _buildDate = source._buildDate
      _buildUser = source._buildUser
      _estimatedHeight = source._estimatedHeight
      _zcashdBuild = source._zcashdBuild
      _zcashdSubversion = source._zcashdSubversion
      _donationAddress = source._donationAddress
      _upgradeName = source._upgradeName
      _upgradeHeight = source._upgradeHeight
      _lightwalletProtocolVersion = source._lightwalletProtocolVersion
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._version) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._vendor) }()
        case 3: try { try decoder.decodeSingularBoolField(value: &_storage._taddrSupport) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._chainName) }()
        case 5: try { try decoder.decodeSingularUInt64Field(value: &_storage._saplingActivationHeight) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._consensusBranchID) }()
        case 7: try { try decoder.decodeSingularUInt64Field(value: &_storage._blockHeight) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._gitCommit) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._branch) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._buildDate) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._buildUser) }()
        case 12: try { try decoder.decodeSingularUInt64Field(value: &_storage._estimatedHeight) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._zcashdBuild) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._zcashdSubversion) }()
        case 15: try { try decoder.decodeSingularStringField(value: &_storage._donationAddress) }()
        case 16: try { try decoder.decodeSingularStringField(value: &_storage._upgradeName) }()
        case 17: try { try decoder.decodeSingularUInt64Field(value: &_storage._upgradeHeight) }()
        case 18: try { try decoder.decodeSingularStringField(value: &_storage._lightwalletProtocolVersion) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._version.isEmpty {
        try visitor.visitSingularStringField(value: _storage._version, fieldNumber: 1)
      }
      if !_storage._vendor.isEmpty {
        try visitor.visitSingularStringField(value: _storage._vendor, fieldNumber: 2)
      }
      if _storage._taddrSupport != false {
        try visitor.visitSingularBoolField(value: _storage._taddrSupport, fieldNumber: 3)
      }
      if !_storage._chainName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._chainName, fieldNumber: 4)
      }
      if _storage._saplingActivationHeight != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._saplingActivationHeight, fieldNumber: 5)
      }
      if !_storage._consensusBranchID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._consensusBranchID, fieldNumber: 6)
      }
      if _storage._blockHeight != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._blockHeight, fieldNumber: 7)
      }
      if !_storage._gitCommit.isEmpty {
        try visitor.visitSingularStringField(value: _storage._gitCommit, fieldNumber: 8)
      }
      if !_storage._branch.isEmpty {
        try visitor.visitSingularStringField(value: _storage._branch, fieldNumber: 9)
      }
      if !_storage._buildDate.isEmpty {
        try visitor.visitSingularStringField(value: _storage._buildDate, fieldNumber: 10)
      }
      if !_storage._buildUser.isEmpty {
        try visitor.visitSingularStringField(value: _storage._buildUser, fieldNumber: 11)
      }
      if _storage._estimatedHeight != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._estimatedHeight, fieldNumber: 12)
      }
      if !_storage._zcashdBuild.isEmpty {
        try visitor.visitSingularStringField(value: _storage._zcashdBuild, fieldNumber: 13)
      }
      if !_storage._zcashdSubversion.isEmpty {
        try visitor.visitSingularStringField(value: _storage._zcashdSubversion, fieldNumber: 14)
      }
      if !_storage._donationAddress.isEmpty {
        try visitor.visitSingularStringField(value: _storage._donationAddress, fieldNumber: 15)
      }
      if !_storage._upgradeName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._upgradeName, fieldNumber: 16)
      }
      if _storage._upgradeHeight != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._upgradeHeight, fieldNumber: 17)
      }
      if !_storage._lightwalletProtocolVersion.isEmpty {
        try visitor.visitSingularStringField(value: _storage._lightwalletProtocolVersion, fieldNumber: 18)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: LightdInfo, rhs: LightdInfo) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._version != rhs_storage._version {return false}
        if _storage._vendor != rhs_storage._vendor {return false}
        if _storage._taddrSupport != rhs_storage._taddrSupport {return false}
        if _storage._chainName != rhs_storage._chainName {return false}
        if _storage._saplingActivationHeight != rhs_storage._saplingActivationHeight {return false}
        if _storage._consensusBranchID != rhs_storage._consensusBranchID {return false}
        if _storage._blockHeight != rhs_storage._blockHeight {return false}
        if _storage._gitCommit != rhs_storage._gitCommit {return false}
        if _storage._branch != rhs_storage._branch {return false}
        if _storage._buildDate != rhs_storage._buildDate {return false}
        if _storage._buildUser != rhs_storage._buildUser {return false}
        if _storage._estimatedHeight != rhs_storage._estimatedHeight {return false}
        if _storage._zcashdBuild != rhs_storage._zcashdBuild {return false}
        if _storage._zcashdSubversion != rhs_storage._zcashdSubversion {return false}
        if _storage._donationAddress != rhs_storage._donationAddress {return false}
        if _storage._upgradeName != rhs_storage._upgradeName {return false}
        if _storage._upgradeHeight != rhs_storage._upgradeHeight {return false}
        if _storage._lightwalletProtocolVersion != rhs_storage._lightwalletProtocolVersion {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension TransparentAddressBlockFilter: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TransparentAddressBlockFilter"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}address\0\u{1}range\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.address) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._range) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.address.isEmpty {
      try visitor.visitSingularStringField(value: self.address, fieldNumber: 1)
    }
    try { if let v = self._range {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: TransparentAddressBlockFilter, rhs: TransparentAddressBlockFilter) -> Bool {
    if lhs.address != rhs.address {return false}
    if lhs._range != rhs._range {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Duration: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Duration"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}intervalUs\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.intervalUs) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.intervalUs != 0 {
      try visitor.visitSingularInt64Field(value: self.intervalUs, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Duration, rhs: Duration) -> Bool {
    if lhs.intervalUs != rhs.intervalUs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension PingResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PingResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}entry\0\u{1}exit\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.entry) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.exit) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.entry != 0 {
      try visitor.visitSingularInt64Field(value: self.entry, fieldNumber: 1)
    }
    if self.exit != 0 {
      try visitor.visitSingularInt64Field(value: self.exit, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PingResponse, rhs: PingResponse) -> Bool {
    if lhs.entry != rhs.entry {return false}
    if lhs.exit != rhs.exit {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Address: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Address"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}address\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.address) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.address.isEmpty {
      try visitor.visitSingularStringField(value: self.address, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Address, rhs: Address) -> Bool {
    if lhs.address != rhs.address {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AddressList: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AddressList"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}addresses\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.addresses) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.addresses.isEmpty {
      try visitor.visitRepeatedStringField(value: self.addresses, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: AddressList, rhs: AddressList) -> Bool {
    if lhs.addresses != rhs.addresses {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Balance: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Balance"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}valueZat\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.valueZat) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.valueZat != 0 {
      try visitor.visitSingularInt64Field(value: self.valueZat, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Balance, rhs: Balance) -> Bool {
    if lhs.valueZat != rhs.valueZat {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension GetMempoolTxRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetMempoolTxRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}exclude_txid_suffixes\0\u{2}\u{2}poolTypes\0\u{c}\u{2}\u{1}")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedBytesField(value: &self.excludeTxidSuffixes) }()
      case 3: try { try decoder.decodeRepeatedEnumField(value: &self.poolTypes) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.excludeTxidSuffixes.isEmpty {
      try visitor.visitRepeatedBytesField(value: self.excludeTxidSuffixes, fieldNumber: 1)
    }
    if !self.poolTypes.isEmpty {
      try visitor.visitPackedEnumField(value: self.poolTypes, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: GetMempoolTxRequest, rhs: GetMempoolTxRequest) -> Bool {
    if lhs.excludeTxidSuffixes != rhs.excludeTxidSuffixes {return false}
    if lhs.poolTypes != rhs.poolTypes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension TreeState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TreeState"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}network\0\u{1}height\0\u{1}hash\0\u{1}time\0\u{1}saplingTree\0\u{1}orchardTree\0\u{1}ironwoodTree\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.network) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.height) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.hash) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.time) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.saplingTree) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.orchardTree) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.ironwoodTree) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.network.isEmpty {
      try visitor.visitSingularStringField(value: self.network, fieldNumber: 1)
    }
    if self.height != 0 {
      try visitor.visitSingularUInt64Field(value: self.height, fieldNumber: 2)
    }
    if !self.hash.isEmpty {
      try visitor.visitSingularStringField(value: self.hash, fieldNumber: 3)
    }
    if self.time != 0 {
      try visitor.visitSingularUInt32Field(value: self.time, fieldNumber: 4)
    }
    if !self.saplingTree.isEmpty {
      try visitor.visitSingularStringField(value: self.saplingTree, fieldNumber: 5)
    }
    if !self.orchardTree.isEmpty {
      try visitor.visitSingularStringField(value: self.orchardTree, fieldNumber: 6)
    }
    if !self.ironwoodTree.isEmpty {
      try visitor.visitSingularStringField(value: self.ironwoodTree, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: TreeState, rhs: TreeState) -> Bool {
    if lhs.network != rhs.network {return false}
    if lhs.height != rhs.height {return false}
    if lhs.hash != rhs.hash {return false}
    if lhs.time != rhs.time {return false}
    if lhs.saplingTree != rhs.saplingTree {return false}
    if lhs.orchardTree != rhs.orchardTree {return false}
    if lhs.ironwoodTree != rhs.ironwoodTree {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension GetSubtreeRootsArg: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetSubtreeRootsArg"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}startIndex\0\u{1}shieldedProtocol\0\u{1}maxEntries\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.startIndex) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.shieldedProtocol) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.maxEntries) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.startIndex != 0 {
      try visitor.visitSingularUInt32Field(value: self.startIndex, fieldNumber: 1)
    }
    if self.shieldedProtocol != .sapling {
      try visitor.visitSingularEnumField(value: self.shieldedProtocol, fieldNumber: 2)
    }
    if self.maxEntries != 0 {
      try visitor.visitSingularUInt32Field(value: self.maxEntries, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: GetSubtreeRootsArg, rhs: GetSubtreeRootsArg) -> Bool {
    if lhs.startIndex != rhs.startIndex {return false}
    if lhs.shieldedProtocol != rhs.shieldedProtocol {return false}
    if lhs.maxEntries != rhs.maxEntries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SubtreeRoot: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SubtreeRoot"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}rootHash\0\u{1}completingBlockHash\0\u{1}completingBlockHeight\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularBytesField(value: &self.rootHash) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.completingBlockHash) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.completingBlockHeight) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.rootHash.isEmpty {
      try visitor.visitSingularBytesField(value: self.rootHash, fieldNumber: 2)
    }
    if !self.completingBlockHash.isEmpty {
      try visitor.visitSingularBytesField(value: self.completingBlockHash, fieldNumber: 3)
    }
    if self.completingBlockHeight != 0 {
      try visitor.visitSingularUInt64Field(value: self.completingBlockHeight, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SubtreeRoot, rhs: SubtreeRoot) -> Bool {
    if lhs.rootHash != rhs.rootHash {return false}
    if lhs.completingBlockHash != rhs.completingBlockHash {return false}
    if lhs.completingBlockHeight != rhs.completingBlockHeight {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension GetAddressUtxosArg: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetAddressUtxosArg"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}addresses\0\u{1}startHeight\0\u{1}maxEntries\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.addresses) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.startHeight) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.maxEntries) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.addresses.isEmpty {
      try visitor.visitRepeatedStringField(value: self.addresses, fieldNumber: 1)
    }
    if self.startHeight != 0 {
      try visitor.visitSingularUInt64Field(value: self.startHeight, fieldNumber: 2)
    }
    if self.maxEntries != 0 {
      try visitor.visitSingularUInt32Field(value: self.maxEntries, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: GetAddressUtxosArg, rhs: GetAddressUtxosArg) -> Bool {
    if lhs.addresses != rhs.addresses {return false}
    if lhs.startHeight != rhs.startHeight {return false}
    if lhs.maxEntries != rhs.maxEntries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension GetAddressUtxosReply: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetAddressUtxosReply"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}txid\0\u{1}index\0\u{1}script\0\u{1}valueZat\0\u{1}height\0\u{1}address\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.txid) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.index) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.script) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.valueZat) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self.height) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.address) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.txid.isEmpty {
      try visitor.visitSingularBytesField(value: self.txid, fieldNumber: 1)
    }
    if self.index != 0 {
      try visitor.visitSingularInt32Field(value: self.index, fieldNumber: 2)
    }
    if !self.script.isEmpty {
      try visitor.visitSingularBytesField(value: self.script, fieldNumber: 3)
    }
    if self.valueZat != 0 {
      try visitor.visitSingularInt64Field(value: self.valueZat, fieldNumber: 4)
    }
    if self.height != 0 {
      try visitor.visitSingularUInt64Field(value: self.height, fieldNumber: 5)
    }
    if !self.address.isEmpty {
      try visitor.visitSingularStringField(value: self.address, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: GetAddressUtxosReply, rhs: GetAddressUtxosReply) -> Bool {
    if lhs.address != rhs.address {return false}
    if lhs.txid != rhs.txid {return false}
    if lhs.index != rhs.index {return false}
    if lhs.script != rhs.script {return false}
    if lhs.valueZat != rhs.valueZat {return false}
    if lhs.height != rhs.height {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension GetAddressUtxosReplyList: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetAddressUtxosReplyList"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}addressUtxos\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.addressUtxos) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.addressUtxos.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.addressUtxos, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: GetAddressUtxosReplyList, rhs: GetAddressUtxosReplyList) -> Bool {
    if lhs.addressUtxos != rhs.addressUtxos {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
