#!/usr/bin/env bash
#
# update-proposal-proto.sh: vendor the FFI proposal.proto from librustzcash.
#
# The canonical definition lives in zcash/librustzcash at
# zcash_client_backend/proto/proposal.proto. libzcashlc encodes proposals with
# whatever schema the pinned zcash_client_backend was built against, so the
# copy compiled into this SDK has to match that exact version: any field the
# copy lacks is a field Swift cannot read.
#
# Unlike the lightwallet protos there is no git subtree to derive from, because
# the upstream version is chosen by a Cargo dependency rather than by a tag this
# repository pulls. The pinned version is therefore read out of Cargo.lock and
# the matching upstream file is fetched over HTTPS.
#
# The derivation adds one thing upstream does not carry: `option swift_prefix`.
# Without it the generated types would collide with the SDK's own names, so
# taking upstream verbatim is not an option.
#
# This script updates the .proto ONLY. The generated proposal.pb.swift is
# committed, so after running this you must regenerate it with protoc and the
# protoc-gen-swift version pinned in Package.resolved; see
# Scripts/update-lightwallet-protocol.sh, which builds that plugin and is the
# reference for how generated sources are produced in this repository.
#
# Usage:
#   ./Scripts/update-proposal-proto.sh           # rewrite the vendored copy
#   ./Scripts/update-proposal-proto.sh --check   # fail if it has drifted (CI)
#
# Both modes are idempotent and neither needs a clean working tree. --check
# writes nothing; it is what the Proto Sync workflow runs.

set -euo pipefail

readonly UPSTREAM_REPO="zcash/librustzcash"
readonly UPSTREAM_PATH="zcash_client_backend/proto/proposal.proto"
readonly CRATE="zcash_client_backend"
readonly LOCK="Cargo.lock"
readonly DEST="Sources/ZODLSwiftWalletSDK/Modules/Service/GRPC/ProtoBuf/proto/proposal.proto"
readonly SWIFT_PREFIX="Ffi"

REPO_ROOT="$(git rev-parse --show-toplevel)"
readonly REPO_ROOT
cd "${REPO_ROOT}"

usage() {
    sed -n '2,31p' "$0" | sed 's|^# \{0,1\}||'
    exit "${1:-1}"
}

# Prints "<version><TAB><source>" for CRATE's entry in Cargo.lock. Cargo.lock
# separates [[package]] blocks with a blank line, which is what delimits a
# record here.
read_lock_entry() {
    awk -v want="${CRATE}" '
        /^\[\[package\]\]$/ { name = ""; version = ""; source = ""; next }
        /^name = / { gsub(/^name = "|"$/, ""); name = $0; next }
        /^version = / { gsub(/^version = "|"$/, ""); version = $0; next }
        /^source = / { gsub(/^source = "|"$/, ""); source = $0; next }
        /^$/ { if (name == want) { print version "\t" source; exit } }
        END { if (name == want) print version "\t" source }
    ' "${LOCK}"
}

# The git ref carrying the proto for the pinned dependency. A crates.io release
# is tagged `<crate>-<version>`; a git dependency pins an exact revision, which
# Cargo.lock records as the fragment of the source URL. Resolving the ref from
# the lockfile rather than from Cargo.toml keeps this correct while a
# librustzcash git override is in use.
upstream_ref() {
    local entry version source
    entry="$(read_lock_entry)"

    if [ -z "${entry}" ]; then
        echo "error: no ${CRATE} entry in ${LOCK}." >&2
        exit 1
    fi

    version="${entry%%$'\t'*}"
    source="${entry#*$'\t'}"

    case "${source}" in
        registry+*)
            echo "${CRATE}-${version}"
            ;;
        git+*)
            if [ "${source}" = "${source#*#}" ]; then
                echo "error: git source for ${CRATE} pins no revision: ${source}" >&2
                exit 1
            fi
            echo "${source##*#}"
            ;;
        *)
            echo "error: unrecognized source for ${CRATE}: '${source}'." >&2
            exit 1
            ;;
    esac
}

# Writes the derived proto for the given upstream ref to stdout.
derive() {
    local ref="$1"
    local url="https://raw.githubusercontent.com/${UPSTREAM_REPO}/${ref}/${UPSTREAM_PATH}"
    local upstream
    upstream="$(mktemp)"
    # shellcheck disable=SC2064 # expand the path now, while it is still in scope
    trap "rm -f '${upstream}'" RETURN

    if ! curl -fsSL "${url}" -o "${upstream}"; then
        echo "error: could not fetch ${url}" >&2
        echo "       Is ${ref} pushed to ${UPSTREAM_REPO}?" >&2
        exit 1
    fi

    if grep -q '^option swift_prefix' "${upstream}"; then
        echo "error: upstream now sets swift_prefix itself." >&2
        echo "       This script's injection is obsolete; vendor it verbatim." >&2
        exit 1
    fi

    if ! grep -q '^package ' "${upstream}"; then
        echo "error: upstream has no 'package' declaration to anchor the injection." >&2
        exit 1
    fi

    cat <<EOF
// DERIVED FILE -- DO NOT EDIT.
//
// Generated by Scripts/update-proposal-proto.sh from
// ${UPSTREAM_REPO}/${UPSTREAM_PATH}
// at the ${CRATE} version pinned in ${LOCK}.
//
// The only change from upstream is the added \`option swift_prefix\` below.
// Bump the dependency and re-run the script rather than editing this file,
// then regenerate proposal.pb.swift.

EOF
    awk -v prefix="${SWIFT_PREFIX}" '
        { print }
        !injected && /^package / {
            print "option swift_prefix = \"" prefix "\";"
            injected = 1
        }
    ' "${upstream}"
}

main() {
    local mode="${1:-update}"
    local ref
    ref="$(upstream_ref)"

    case "${mode}" in
        update)
            derive "${ref}" > "${DEST}"
            echo "Derived ${DEST} from ${UPSTREAM_REPO}@${ref}."
            echo
            echo "proposal.pb.swift is committed and is NOT regenerated by this"
            echo "script. Regenerate it with the protoc-gen-swift version pinned"
            echo "in Package.resolved before committing; see"
            echo "Scripts/update-lightwallet-protocol.sh for how this repository"
            echo "builds that plugin."
            ;;
        check)
            local derived
            derived="$(mktemp)"
            # shellcheck disable=SC2064 # expand the path now, while it is in scope
            trap "rm -f '${derived}'" EXIT
            derive "${ref}" > "${derived}"

            if diff -u "${DEST}" "${derived}"; then
                echo "${DEST} matches ${UPSTREAM_REPO}@${ref}."
            else
                echo >&2
                echo "error: ${DEST} has drifted from ${UPSTREAM_REPO}@${ref}," >&2
                echo "       the ${CRATE} version pinned in ${LOCK}." >&2
                echo "       Run ./Scripts/update-proposal-proto.sh, regenerate" >&2
                echo "       proposal.pb.swift, and commit both." >&2
                exit 1
            fi
            ;;
    esac
}

case "${1:-}" in
    -h|--help)
        usage 0
        ;;
    --check)
        main check
        ;;
    '')
        main update
        ;;
    *)
        echo "error: unknown option '$1'." >&2
        usage 1
        ;;
esac
